// Auto-generated changelog file
// This file is automatically generated during the build process from CHANGELOG.md
// Do not edit manually

export interface ChangelogEntry {
  version: string;
  date: string;
  content: {
    en: string;
    zh: string;
  };
}

export const CHANGELOG_DATA: ChangelogEntry[] = [
  {
    version: '0.3.2',
    date: '2026-03-25',
    content: {
      en: `✨ Features
- Add provider runtime state detection: introduce getClaudeRuntimeState() to determine access mode (managed/local/cli_login/inactive); limit proxy/TLS env injection to local and cli_login modes; clear injected env vars on each setupApiKey() call to prevent stale value leaks
- Rename ANTHROPIC_DEFAULT_HAIKU_MODEL → ANTHROPIC_SMALL_FAST_MODEL across provider presets, ProviderDialog, types and model state hooks; keep legacy key for backward compatibility

🐛 Fixes
- Fix provider model mapping section always hidden: set showModelMappingSection to always true; return CUSTOM_PROXY_PRESET_ID for unrecognized proxy endpoints to keep model mapping enabled for third-party configs
- Fix terminal monitor EDT threading and lifecycle leaks: avoid blocking widget discovery on EDT, bind listeners to project/widget lifecycles #gadfly3173 (#774)
- Fix scrollbar cursor showing I-beam instead of arrow: move cursor:text to .markdown-content; retain I-beam on code content only #jhaan83 (#767)
- Fix session index corruption from invalid Unicode titles #gadfly3173 (#769)
- Fix permission watcher thread not stopping promptly on disposal: interrupt thread and handle InterruptedException (#781)

⚡ Performance
- Optimize streaming and UUID sync: add StreamDeltaThrottler to batch stream deltas; replace full history load with getLatestUserMessage for UUID sync; add patchMessageUuid webview callback; add active request tracking in DaemonBridge with extended heartbeat timeout

🔧 Improvements
- Add unit tests for StreamDeltaThrottler, DaemonBridge, and MessageJsonConverter
- Remove unused CursorHandler
- Update action icons with unified cc-gui-icon.svg; redesign cc-gui-icon.svg
- Rename "Send to CCG" to "Send File Path to CC GUI" across all 9 languages; rename CCG → CC GUI in all i18n strings`,
      zh: `✨ Features
- 新增 Provider 运行时状态检测：引入 getClaudeRuntimeState() 判断访问模式（managed/local/cli_login/inactive），仅在 local 和 cli_login 模式下注入代理/TLS 环境变量，每次 setupApiKey() 调用时清除注入变量防止泄漏
- 重命名 ANTHROPIC_DEFAULT_HAIKU_MODEL → ANTHROPIC_SMALL_FAST_MODEL，覆盖 Provider 预设、ProviderDialog、类型和模型状态 hooks；保留旧 key 兼容性

🐛 Fixes
- 修复 Provider 模型映射区域始终隐藏：强制 showModelMappingSection 为 true；对无法识别的代理端点返回 CUSTOM_PROXY_PRESET_ID，确保第三方代理配置下模型映射保持启用
- 修复终端监控器 EDT 线程问题及生命周期泄漏：避免在 EDT 上阻塞 Widget 发现，将监听器绑定至项目和 Widget 生命周期 #gadfly3173 (#774)
- 修复滚动条光标显示为输入光标而非箭头：将 cursor:text 移至 .markdown-content，仅代码内容保留输入光标 #jhaan83 (#767)
- 修复会话索引因无效 Unicode 标题导致写入损坏 #gadfly3173 (#769)
- 修复权限监视器线程无法及时停止：停止时中断线程并处理 InterruptedException (#781)

⚡ Performance
- 优化流式传输和 UUID 同步：新增 StreamDeltaThrottler 批处理流增量；使用 getLatestUserMessage 替代全量历史加载进行 UUID 同步；新增 patchMessageUuid webview 回调；DaemonBridge 新增活跃请求跟踪并延长心跳超时

🔧 Improvements
- 新增 StreamDeltaThrottler、DaemonBridge、MessageJsonConverter 单元测试
- 移除未使用的 CursorHandler
- 统一使用新版 cc-gui-icon.svg 更新操作图标；重新设计图标视觉风格
- 将"Send to CCG"重命名为"Send File Path to CC GUI"，9 种语言全部更新；将 i18n 字符串中 CCG 统一重命名为 CC GUI`,
    },
  },
  {
    version: '0.3.1',
    date: '2026-03-23',
    content: {
      en: `✨ Features
- Add CLI Login provider: delegate auth to Claude SDK's native OAuth flow, with account info display and authorize/revoke dialogs; update i18n across 9 languages
- Add provider deactivation support: deactivateClaudeProvider() sets current provider to empty, add confirmation dialogs for switching to/from local provider, simplify settings UI
- Add Korean language support #KimTibber

🐛 Fixes
- Fix UI stuck in responding/thinking state: resolve race conditions in DaemonBridge, ClaudeMessageHandler, StreamMessageCoalescer, and streamingCallbacks.ts
- Fix race condition where last streaming assistant message is lost: move ref cleanup into setMessages updater, add fallback recovery path #gadfly3173
- Fix JCEF WebView incorrect cursor types on macOS: add CefDisplayHandler to map Chromium cursors to Swing (#753) #yogendrasinghx
- Fix Codex history initial load returning fewer sessions than refresh: replace root-dir timestamp check with file-count comparison #gadfly3173
- Fix MSYS2/Git Bash path conversion: handle ~, /home/<user>, /tmp, /dev/null mappings; consolidate temp dir resolution into PlatformUtils.getTempDirectory() #gadfly3173
- Fix node path validation regression: reject invalid saved node paths and keep bridge state in sync #gadfly3173
- Fix plugin installation and UI interaction reliability: versioned plugin dirs, thinking block state, enqueue dialog requests #hpstream
- Rename "Auto Open File" to "Send Opened File Path" across all 8 locales (#693) #gadfly3173

🔧 Improvements
- Large-scale refactoring: ClaudeSDKBridge (1600+ lines) → 12 classes, DiffHandler → 7 modules, ClaudeSession → 5 modules, SlashCommandRegistry → 6 classes, CodexHistoryReader → 4 modules, PersistentQueryService and ChatInputBox split into focused modules
- Reorganize Java package structure by domain (action, ui, handler subpackages)
- Normalize model resolution: keep canonical model ID in Java, add env config normalization helpers with tests
- Extract CursorHandler and throttle mousemove with requestAnimationFrame
- Translate Chinese comments and JSDoc to English across 14 files
- Rename plugin ID and project name to idea-claude-code-gui`,
      zh: `✨ Features
- 新增 CLI Login Provider：通过 Claude SDK 原生 OAuth 认证，ProviderList 显示账户信息及授权/撤销对话框，更新 9 种语言 i18n
- 新增 Provider 停用支持：切换本地 Provider 时显示确认对话框，将 Provider 信息集成至 ProviderList 简化设置界面
- 新增韩语支持 #KimTibber

🐛 Fixes
- 修复 UI 卡在"响应中/思考中"状态：修复 DaemonBridge、ClaudeMessageHandler、StreamMessageCoalescer 及 streamingCallbacks.ts 多处竞态
- 修复流结束时最后一条助手消息丢失的竞态问题 #gadfly3173
- 修复 JCEF WebView 在 macOS 上光标类型不正确 (#753) #yogendrasinghx
- 修复 Codex 历史记录首次加载比刷新少会话 #gadfly3173
- 修复 MSYS2/Git Bash 路径转换：处理 ~、/tmp、/dev/null 等映射 #gadfly3173
- 修复 Node 路径验证回归：拒绝保存无效路径 #gadfly3173
- 修复插件安装和 UI 交互可靠性：支持带版本号插件目录、对话框请求入队 #hpstream
- 将"Auto Open File"重命名为"Send Opened File Path"，8 种语言全部更新 (#693) #gadfly3173

🔧 Improvements
- 大规模后端重构：ClaudeSDKBridge（1600+行）→ 12 个类，DiffHandler → 7 个模块，ClaudeSession → 5 个模块，SlashCommandRegistry → 6 个类，CodexHistoryReader → 4 个模块
- 按领域重组 Java 包结构（action、ui、handler 子包）
- 规范化模型解析和环境变量配置，新增辅助函数和单元测试
- 提取 CursorHandler，使用 requestAnimationFrame 节流 mousemove 监听
- 将 14 个文件中文注释和 JSDoc 统一翻译为英文
- 重命名插件 ID 和项目名称为 idea-claude-code-gui`,
    },
  },
  {
    version: '0.3',
    date: '2026-03-16',
    content: {
      en: `✨ Features
- Add file context placeholder with enable confirmation popover in ContextBar: show a dashed placeholder when autoOpenFile is disabled, with i18n support for 8 locales
- Replace raw error with friendly provider-not-configured card: amber-toned warning with "Go to Provider Settings" button for first-run experience

🐛 Fixes
- Fix active sessions interrupted when request exceeds 30 minutes: add turn tracking and 6-hour runtime lifetime cap (#672) #JackCmd233
- Fix token usage tracking in streaming multi-turn conversations: properly accumulate usage across turns (#686)
- Fix CRLF/LF line ending mismatch in diff review on Windows (#687) #gadfly3173
- Fix session title data loss from race conditions: atomic write and ReentrantLock for concurrent operations
- Fix Codex session transition guard blocking history restore

🔧 Improvements
- Extract shared ProviderModelIcon component supporting 19 model vendors with pattern-based icon resolution
- Extract line-ending normalization helper to eliminate duplicated CRLF/LF conversion logic`,
      zh: `✨ Features
- 上下文栏新增文件上下文占位符及启用确认弹窗：autoOpenFile 关闭时显示虚线占位按钮，支持 8 种语言国际化
- 未配置 Provider 时显示友好提示卡片：琥珀色警告卡片替代红色错误，优化首次使用体验

🐛 Fixes
- 修复单次请求超过 30 分钟时打断正在运行的会话：添加 turn 跟踪及 6 小时运行时生命周期上限 (#672) #JackCmd233
- 修复流式多轮对话中 Token 用量统计错误：正确累积各 turn 用量 (#686)
- 修复 Windows 上 Diff Review 因换行符不匹配无法打开 (#687) #gadfly3173
- 修复会话标题因竞态条件丢失：原子写入 + ReentrantLock 序列化并发操作
- 修复 Codex 会话恢复时 transition guard 阻塞历史消息

🔧 Improvements
- 提取共享 ProviderModelIcon 组件，支持 19 家模型厂商 pattern 图标解析
- 提取换行符规范化辅助函数，消除重复 CRLF/LF 转换逻辑`,
    },
  },
  {
    version: '0.2.9',
    date: '2026-03-15',
    content: {
      en: `✨ Features
- Rename project to CC GUI (originally Claude Code GUI) to mitigate trademark risks
- Change default Codex sandbox mode to danger-full-access for broader permissions
- Add GitHub repository section to community settings with copy-to-clipboard URL
- Default autoOpenFile to disabled

🐛 Fixes
- Fix daemon zombie node processes consuming 100% CPU (#634) #3499623985
- Fix streaming assistant placeholder lost during updateMessages (#650)
- Fix Codex stdio MCP server status stays on pending (#653) #pwang1984
- Fix default provider for first-time users (#639) #JackCmd233
- Fix model switch not taking effect (#638) #hpstream
- Fix cwd fallback when active file is outside project root (#636) #jhaan83
- Fix READ_ONLY tools permission in default vs acceptEdits mode

🔧 Improvements
- Refactor ProviderHandler into 7 focused modules
- Refactor SettingsHandler into 4 focused modules
- Refactor useWindowCallbacks into registerCallbacks sub-modules with extracted settings hooks
- Refactor FileHandler, HistoryHandler, ClaudeHistoryReader, App.tsx into focused modules (major size reduction)
- Extract Claude model mapping to utility module with tests (#639) #JackCmd233`,
      zh: `✨ Features
- 项目重命名为 CC GUI（原 Claude Code GUI），规避商标风险
- Codex 默认沙箱模式改为 danger-full-access，减少权限使用阻力
- 社区设置页新增 GitHub 开源地址，支持一键复制
- autoOpenFile 默认值改为关闭

🐛 Fixes
- 修复 daemon 僵尸进程导致 100% CPU 占用 (#634) #3499623985
- 修复流式助手消息占位符在 updateMessages 时丢失 (#650)
- 修复 Codex stdio MCP 服务器状态持续 pending (#653) #pwang1984
- 修复首次用户默认 Provider (#639) #JackCmd233
- 修复切换模型不生效 (#638) #hpstream
- 修复活动文件在项目外时 cwd 回退错误 (#636) #jhaan83
- 修复 READ_ONLY 工具权限：默认模式需确认，acceptEdits 模式自动批准

🔧 Improvements
- 重构 ProviderHandler 为 7 个聚焦模块
- 重构 SettingsHandler 为 4 个聚焦模块
- 重构 useWindowCallbacks 为 registerCallbacks 子模块，提取设置 hooks
- 重构 FileHandler、HistoryHandler、ClaudeHistoryReader、App.tsx 为聚焦模块（大幅缩减体积）
- 提取 Claude 模型映射到工具模块并添加测试 (#639) #JackCmd233`,
    },
  },
  {
    version: '0.2.8',
    date: '2026-03-12',
    content: {
      en: `🐛 Fixes
- Change registrant.npmmirror.com to registry.npmjs.org
- Change the remote images used to join WeChat groups on the settings page to local images
- Fix network env vars injection timing: inject proxy and TLS settings before any HTTPS connection to fix corporate SSL-inspection proxy issues, add URL validation and security warning for disabled TLS verification

🔧 Improvements
- Refactor Claude message-service into focused submodules: message-utils, message-permission, message-session-registry, message-sender, message-sender-anthropic, message-rewind
- Refactor Codex message-service into focused submodules: codex-agents-loader, codex-command-utils, codex-event-handler, codex-patch-parser, codex-utils
- Refactor permission-handler into focused modules: permission-ipc and permission-safety
- Refactor UsageStatisticsSection into tab components: UsageOverviewTab, UsageModelsTab, UsageSessionsTab, UsageTimelineTab, useUsageStatistics hook
- Refactor useInputHistory: extract pure storage functions to inputHistoryStorage.ts
- Refactor fileIcons: extract icon maps to fileIconMaps.ts`,
      zh: `🐛 Fixes
- 将 registry.npmmirror.com 修改为 registry.npmjs.org
- 将设置页面用于加入微信群的远程图片，改为本地图片
- 修复网络环境变量注入时机：在任何 HTTPS 连接之前注入代理和 TLS 设置，修复企业 SSL 检查代理问题，新增代理 URL 验证和 TLS 验证禁用安全警告

🔧 Improvements
- 重构 Claude message-service 为聚焦子模块：message-utils、message-permission、message-session-registry、message-sender、message-sender-anthropic、message-rewind
- 重构 Codex message-service 为聚焦子模块：codex-agents-loader、codex-command-utils、codex-event-handler、codex-patch-parser、codex-utils
- 重构 permission-handler 为聚焦模块：permission-ipc 和 permission-safety
- 重构 UsageStatisticsSection 为 Tab 组件：UsageOverviewTab、UsageModelsTab、UsageSessionsTab、UsageTimelineTab、useUsageStatistics hook
- 重构 useInputHistory：将纯存储函数提取到 inputHistoryStorage.ts
- 重构 fileIcons：将图标映射提取到 fileIconMaps.ts`,
    },
  },
  {
    version: '0.2.7',
    date: '2026-03-10',
    content: {
      en: `✨ Features
- Project-level prompt storage: dual-scope prompt management (global + project), store project prompts in for team sharing via Git, separate UI sections with full CRUD, chat autocomplete with scope labels (#598) #hpstream
- Codex mode enhancements: suggest (approval) mode, per-conversation permission isolation, separate Codex/Claude Code config UI, agent config and diff editor panel in Codex mode (#571) #tonyshengbo
- Improve Codex tool rendering with smart classification and file navigation (#607) #gadfly3173
- Add AUTO_ALLOW_TOOLS category and improve plan mode permissions (#609) #gadfly3173
- Add Agent tool alias for Task in plan mode (#615) #gadfly3173
- Add provider sorting functionality with drag-and-drop reorder (#617) #fanchenggang
- Add apiKeyHelper support for enterprise authentication (#623) #bdelamarre
- Update Codex model list: add gpt-5.4, remove gpt-5.2/gpt-5.3

🐛 Fixes
- Fix Codex stdio MCP server status stays on pending: add handshake request (#499) #pwang1984
- Fix Windows sound path issue for completion notification (#553) #z231485
- Prepend configured Node.js path to ensure version priority (#587) #gadfly3173
- Resolve session transition races, streaming stability, and error deduplication (#600) #gadfly3173
- Enhance SDK update and version handling (#602) #gadfly3173
- Add runtime session epoch isolation to prevent ghost messages (#611) #gadfly3173
- Fix context menu cut function and enhance file tag handling (#625) #JackCmd233
- Enforce UTF-8 charset for all file I/O operations
- Replace experimental IntelliJ APIs with stable alternatives
- Harden Codex path resolution and improve sandbox defaults

🔧 Improvements
- Refactor PromptManager to AbstractPromptManager with template methods, GlobalPromptManager, ProjectPromptManager, PromptManagerFactory (#598) #hpstream
- Extract shared provider sorting logic to reduce duplication
- Extract shared command tool names and improve parsing robustness
- Extract apiKeyHelper detection and add missing i18n keys
- Replace hardcoded VSCode variables with design tokens in dialogs
- Improve code quality with thread safety, defensive copying, and log cleanup`,
      zh: `✨ Features
- 项目级别提示词存储：双作用域提示词管理（全局 + 项目），项目提示词存储在 文件中可通过 Git 团队共享，全局和项目提示词分区展示并支持完整增删改查，聊天自动补全带作用域标签 (#598) #hpstream
- Codex 模式增强：支持 suggest（审批）模式、会话级独立权限审批、拆分 Codex 和 Claude Code 配置界面、Codex 模式下智能体配置和 diff 编辑面板 (#571) #tonyshengbo
- 改进 Codex 工具渲染：智能分类和文件导航 (#607) #gadfly3173
- 新增 AUTO_ALLOW_TOOLS 类别并改进 Plan 模式权限 (#609) #gadfly3173
- Plan 模式支持 Agent 工具作为 Task 的别名 (#615) #gadfly3173
- 新增 Provider 排序功能：支持拖拽排序 (#617) #fanchenggang
- 新增 apiKeyHelper 企业认证支持 (#623) #bdelamarre
- 更新 Codex 模型列表：新增 gpt-5.4，移除 gpt-5.2/gpt-5.3

🐛 Fixes
- 修复 Codex stdio MCP 服务器状态持续 pending 问题 (#499) #pwang1984
- 修复 Windows 平台设置完成语音路径问题 (#553) #z231485
- 修复配置的 Node.js 路径优先级 (#587) #gadfly3173
- 修复会话切换竞态、流式稳定性和错误去重 (#600) #gadfly3173
- 增强 SDK 更新和版本处理 (#602) #gadfly3173
- 新增运行时会话 epoch 隔离以防止幽灵消息 (#611) #gadfly3173
- 修复上下文菜单剪切功能并增强文件标签处理 (#625) #JackCmd233
- 强制所有文件 I/O 操作使用 UTF-8 编码
- 替换实验性 IntelliJ API 为稳定替代方案
- 加固 Codex 路径解析并改进沙箱默认值

🔧 Improvements
- 重构 PromptManager 为 AbstractPromptManager 抽象基类 (#598) #hpstream
- 提取共享的 Provider 排序逻辑以减少重复代码
- 提取共享命令工具名称并改进解析健壮性
- 提取 apiKeyHelper 检测逻辑并补充缺失的 i18n 键
- 将对话框中硬编码的 VSCode 变量替换为设计令牌
- 改进代码质量：线程安全、防御性拷贝和日志清理`,
    },
  },
  {
    version: '0.2.6',
    date: '2026-03-05',
    content: {
      en: `✨ Features
- Support pasting clipboard images in chat input: convert clipboard image data to base64 PNG, dispatch to webview and add as attachment
- Add subscription tutorial dialog for Claude and Codex providers: tabbed step-by-step instructions with code block copy, i18n for 8 languages
- Align slash command scanning with CLI behavior: plugin namespace prefixing, recursive directory scanning with SKILL.md detection, marketplace manifest fallback (#579) #gadfly3173
- Add configurable "play sound only when IDE unfocused" setting (#583) #PaulGiletich

🐛 Fixes
- Gate Write tool with permission check in plan mode: add Write to permission check branch, add findProjectByPath fallback and retry logic (#580) #gadfly3173
- Align token usage display with CLI behavior: reset per-turn accumulator on message_start, emit final usage before STREAM_END, show token info in status bar (#578) #gadfly3173
- Fix token usage display in streaming and non-streaming modes: fix EDT violation, avoid duplicate updates, add monotonic increase check
- Offload MCP server I/O to background threads: CompletableFuture.runAsync, 5-second timeout for command availability check
- Harden plugin command scanning with depth limit and path safety
- Address code review issues: GSON encoding for base64 JS injection prevention, fix i18n condition checks, replace hardcoded colors with theme variables
- Normalize sound config response format and replace inline style with CSS Module class

🔧 Improvements
- Refactor tool block collapse UI: all tools with params collapsible, chevron icon with CSS accordion animation
- Add CSS variables for notice-box colors with dark/light theme support, responsive layout for usage tabs
- Fix CSS class naming collision in usage stats, change default date range from 30d to 7d`,
      zh: `✨ Features
- 支持在聊天输入框粘贴剪贴板图片：剪贴板图片数据转换为 base64 PNG，分发到 webview 作为附件
- 新增 Claude 和 Codex 订阅教程对话框：分标签页操作说明，代码块复制，8 种语言国际化
- 对齐斜杠命令扫描与 CLI 行为：插件命名空间前缀、递归目录扫描支持 SKILL.md 检测、市场清单回退 (#579) #gadfly3173
- 新增 "仅在 IDE 失焦时播放提示音" 配置项 (#583) #PaulGiletich

🐛 Fixes
- 修复 Plan 模式下 Write 工具权限检查：将 Write 加入权限检查分支，添加 findProjectByPath 回退和重试逻辑 (#580) #gadfly3173
- 修复 Token 用量显示对齐 CLI 行为：message_start 时重置累计器，STREAM_END 前发送最终用量，状态栏显示 Token 信息 (#578) #gadfly3173
- 修复流式和非流式模式下 Token 用量显示：修复 EDT 线程违规，避免重复更新，添加单调递增检查
- MCP 服务器 I/O 操作移至后台线程：CompletableFuture.runAsync，命令检查添加 5 秒超时
- 加固插件命令扫描安全：深度限制和路径安全防护
- 修复代码审查中安全和质量问题：GSON 编码防 JS 注入，修复 i18n 条件检查，硬编码颜色替换为主题变量
- 规范化声音配置响应格式，内联样式替换为 CSS Module 类

🔧 Improvements
- 重构工具块折叠 UI：所有含参数的工具可折叠，箭头图标和 CSS 手风琴动画
- 为 notice-box 颜色添加 CSS 变量，支持深色/浅色主题，窄视口响应式布局
- 修复使用统计 CSS 类名冲突，默认日期范围从 30 天改为 7 天`,
    },
  },
  {
    version: '0.2.5',
    date: '2026-03-04',
    content: {
      en: `✨ Features
- Tab detach to floating window: detach chat tabs into independent floating windows for multi-window parallel conversations (#564) #hpstream
- Register IDEA keyboard shortcuts for chat tool window: Ctrl+C/X/V/Enter, right-click context menu, clipboard handler via JS bridge (#541) #gadfly3173
- Persist chat input attachments across view switches: save/restore via localStorage with 2MB limit (#542) #hpstream
- Support agent tool type and improve task block UI: display actual tool name, expand/collapse chevron
- Add SDK update functionality with uninstall-reinstall strategy and progress feedback
- Increase Codex maxTurns from 20 to 200 for long-running tasks

🐛 Fixes
- Accumulate streaming token usage from message_start and message_delta events (#559) #gadfly3173
- Preserve Node.js version cache when new IDEA window opens (#562) #gadfly3173
- Support Ctrl+C/X/V in native input and textarea elements (#560) #gadfly3173
- Defer JCEF browser creation to avoid service initialization conflict (#569) #gadfly3173
- Replace type assertions with runtime type checks to prevent crashes from MCP tool calls (#567) #gadfly3173
- Prevent UI freeze when opening settings on macOS in Codex mode: singleton NodeDetector, async handler offloading, in-flight dedup (#543) #gadfly3173
- Restore Claude slash-command skill discovery for plugin skills: multi-directory traversal, plugin manifest resolution, context-aware filtering (#551) #gadfly3173
- Harden skill discovery against path traversal and resource exhaustion: plugin ID validation, traversal depth limits, YAML alias limits
- Resolve race condition in Node.js path caching during manual configuration
- Improve async robustness and fix stale closure in DependencySection: 30s timeout, binary validation, CompletableFuture tracking
- Harden WebView bridge security and context menu accessibility: JS function name validation, extended string escaping, clipboard rate limiting, ARIA roles
- Fix detached window issues: memory leak, race condition, double dispose guards (#564)

🔧 Improvements
- Optimize SVG icon with CSS classes and simplified paths
- Stabilize attachment callbacks with useCallback
- Replace remote banner image with local asset`,
      zh: `✨ Features
- Tab 分离到浮动窗口：将聊天标签页分离为独立浮动窗口，支持多窗口跨屏幕并行对话 (#564) #hpstream
- 注册 IDEA 键盘快捷键到聊天工具窗口：Ctrl+C/X/V/Enter、右键上下文菜单、JS 桥接剪贴板读写 (#541) #gadfly3173
- 切换页面后保留输入框图片附件：localStorage 保存/恢复，2MB 大小限制 (#542) #hpstream
- 支持 agent 工具类型并改进任务块 UI：显示实际工具名，展开/折叠箭头图标
- 新增 SDK 更新功能（卸载后重装策略），支持进度反馈
- Codex maxTurns 从 20 提升到 200，支持长时间任务

🐛 Fixes
- 修复流式 Token 用量累计：正确累计 message_start 和 message_delta 事件中的 Token (#559) #gadfly3173
- 修复新 IDEA 窗口打开时 Node.js 版本缓存丢失 (#562) #gadfly3173
- 修复原生 input/textarea 中 Ctrl+C/X/V 不工作 (#560) #gadfly3173
- 修复 JCEF 浏览器创建时服务初始化冲突 (#569) #gadfly3173
- 修复类型断言导致 MCP 工具调用崩溃，改用运行时类型检查 (#567) #gadfly3173
- 修复 macOS 下 Codex 模式打开设置时 UI 冻结：NodeDetector 单例共享缓存、异步化、并发去重 (#543) #gadfly3173
- 恢复 Claude 斜杠命令对插件 Skills 的发现：多目录遍历、插件清单解析、上下文感知过滤 (#551) #gadfly3173
- 加固 Skill 发现路径遍历和资源耗尽防护：插件 ID 验证、遍历深度限制、YAML 别名限制
- 修复手动配置时 Node.js 路径缓存竞态条件
- 改进异步健壮性并修复 DependencySection 闭包过期：30 秒超时、二进制名验证、CompletableFuture 追踪
- 加固 WebView 桥接安全和上下文菜单无障碍：JS 函数名验证、扩展字符串转义、剪贴板限流、ARIA 角色
- 修复浮动窗口问题：内存泄漏、竞态条件、双重销毁守卫 (#564)

🔧 Improvements
- 优化 SVG 图标：CSS 类和简化路径
- useCallback 稳定附件回调，避免不必要重渲染
- 用本地资源替换远程 Banner 图片`,
    },
  },
  {
    version: '0.2.4',
    date: '2026-03-02',
    content: {
      en: `✨ Features
- Replace remote SDK slash command fetching with fully local registry: parse SKILL.md frontmatter via SnakeYAML, scan personal and project skill directories, push commands on session creation and provider switch #gadfly3173
- Add Codex skills support with multi-level directory scanning, $ prefix invocation, config.toml enable/disable integration, and dual-mode UI #gadfly3173
- Improve process lifecycle and resource cleanup: tab disposal handler for daemon shutdown, forceful kill of unresponsive daemons, proper bridge cleanup in all paths
- Add Qwen and OpenRouter as new provider presets with i18n translations for 8 languages
- Highlight auto mode selector in orange as visual permission warning cue
- Add security notice to provider dialog and estimate disclaimer to usage statistics

🐛 Fixes
- Resolve real OS home directory to bypass IDEA's user.home override: read USERPROFILE/HOME env vars, replace all 35 direct calls across 22 files, add checkstyle enforcement #gadfly3173
- Prevent stale loading panel blocking error UI on Node.js detection failure #gadfly3173
- Resolve permission mode state desync between frontend and backend: unified push/pull flow with priority rule (payload > session > default) #gadfly3173
- Apply date range filter on server side for usage statistics (#534) #gadfly3173
- Fix tab title management: prevent manual rename overwrite by AI status, fix double ellipsis #Olexandr1904
- Sync permission mode state in reused daemon runtime hooks
- Decouple status panel expanded state from content presence
- Remove model ID format regex restriction for third-party providers
- Allow symbolic links in Codex skill directory scanning
- Harden input validation: path traversal prevention, directory whitelist, permission mode whitelist, config dropdown scroll

🔧 Improvements
- Extract token usage utilities into dedicated TokenUsageUtils class #gadfly3173
- Unify permission mode validation across frontend and backend with shared constants
- Replace alert dialogs with toast notifications and inline feedback
- Remove useUsageStats hook (no-op after polling removal) #gadfly3173
- Harden Codex skills security: YAML parser DoS limits, path traversal checks, LoadingState tracking
- Redesign app icon to simplified stroke-based SVG
- Move payment QR codes from README to SPONSORS.md`,
      zh: `✨ Features
- 用本地注册表替代远程 SDK 斜杠命令获取：SnakeYAML 解析 SKILL.md frontmatter，扫描个人和项目 skill 目录，会话创建和供应商切换时主动推送 #gadfly3173
- 新增 Codex Skills 支持：多层级目录扫描、$ 前缀调用、config.toml 启用/禁用集成、双模式 UI #gadfly3173
- 改进进程生命周期和资源清理：标签页关闭时销毁 daemon、强制终止无响应 daemon、所有路径正确清理 bridge 资源
- 新增通义千问（Qwen）和 OpenRouter 供应商预设，支持 8 种语言国际化
- Auto 模式选择器以橙色高亮，作为权限放开的视觉警示
- 供应商对话框添加安全提示，使用统计添加估算免责声明

🐛 Fixes
- 修复 IDEA 覆盖 user.home 导致主目录解析错误：读取 USERPROFILE/HOME 环境变量，替换全部 35 处调用（22 个文件），新增 checkstyle 强制约束 #gadfly3173
- 修复 Node.js 检测失败时加载面板阻塞错误 UI #gadfly3173
- 修复前后端权限模式状态不同步：统一推/拉流程，优先级规则 payload > session > default #gadfly3173
- 修复使用统计日期范围过滤：服务端聚合前过滤会话 (#534) #gadfly3173
- 修复标签页标题管理：手动重命名不再被 AI 状态覆盖，修复双省略号 #Olexandr1904
- 修复复用 daemon 运行时 hooks 权限模式状态过期问题
- 解耦状态面板展开状态与内容存在性，由用户偏好控制
- 移除模型 ID 格式正则限制，支持第三方供应商格式
- 允许 Codex skill 目录扫描识别符号链接
- 加固输入验证：路径遍历防护、目录白名单、权限模式白名单、下拉框滚动溢出

🔧 Improvements
- 提取 Token 使用工具到独立 TokenUsageUtils 类，支持多供应商复用 #gadfly3173
- 统一前后端权限模式验证，提取共享常量和类型守卫
- 用 toast 通知和内联反馈替代 alert 弹窗
- 移除 useUsageStats hook（后台轮询移除后已成空操作） #gadfly3173
- 加固 Codex Skills 安全性：YAML 解析器 DoS 限制、路径遍历检查、加载状态追踪
- 重新设计应用图标为简化描边风格 SVG
- 将支付二维码从 README 移至 SPONSORS.md`,
    },
  },
  {
    version: '0.2.3',
    date: '2026-02-27',
    content: {
      en: `✨ Features
- Add daemon mode to eliminate per-request Node.js process spawning: persistent daemon with NDJSON protocol, heartbeat monitoring, auto-restart, and three-phase prewarm strategy for low-latency first messages
- Add abort/cancel support for daemon mode: interrupt active SDK query immediately instead of waiting for completion
- Split BasicConfigSection into tabbed layout (Appearance/Behavior/Environment) for improved settings navigation

🐛 Fixes
- Fix Windows sound notification not playing after AI task completion, switch to native Java audio playback for cross-platform stability #z231485
- Fix sound notification delay, trigger immediately after stream ends #z231485
- Fix sound notification reliability: add 30s MP3 playback timeout, prevent duplicate success+error notifications
- Fix: only show Windows path constraints on Windows platform #hpstream
- Fix: support filenames with spaces in file tag matching with smart longest-match path resolution #hpstream
- Fix: resolve model name from settings.json for third-party API proxy compatibility
- Fix: inject proxy env vars from settings.json for IDE desktop launcher (#429)
- Fix model mapping fallback: only apply sonnet mapping when model ID contains 'sonnet'
- Complete autoOpenFile i18n translations for es/fr/hi/ja/zh-TW

🔧 Improvements
- Optimize file tag matching performance and add unit tests
- Extract shared Windows path constraint into prompt-utils utility
- Deduplicate loadClaudeSettings() calls in sendMessage methods
- Simplify streamEndCallback from Consumer<Boolean> to Runnable`,
      zh: `✨ Features
- 新增 Daemon 常驻进程模式：消除每次请求的 Node.js 启动开销（5-10 秒），NDJSON 协议通信，心跳监控、自动重启、三阶段预热
- 新增 Daemon 模式请求中断支持：立即停止活跃的 SDK 查询
- 重构基础设置页面为选项卡布局（外观/行为/环境），改善设置导航

🐛 Fixes
- 修复 Windows 下 AI 任务完成后提示音不播放，改用原生 Java 音频库 #z231485
- 修复提示音延迟，改为流结束后立即触发 #z231485
- 提升提示音可靠性：30 秒播放超时，防止成功+错误通知冲突
- 修复 Windows 路径约束提示仅在 Windows 平台显示 #hpstream
- 修复文件标签匹配支持带空格的文件名 #hpstream
- 修复第三方 API 代理兼容性：从 settings.json 读取模型映射名称
- 修复 IDE 桌面启动器代理环境变量注入 (#429)
- 修复模型映射回退：仅 sonnet 模型应用映射
- 补充 autoOpenFile 多语言翻译（es/fr/hi/ja/zh-TW）

🔧 Improvements
- 优化文件标签匹配性能，新增单元测试
- 提取 Windows 路径约束到共享工具函数，消除重复
- 合并重复的 loadClaudeSettings() 调用
- 简化 streamEndCallback 类型`,
    },
  },
  {
    version: '0.2.2',
    date: '2026-02-25',
    content: {
      en: `✨ Features
- Add task completion sound notification with 5 built-in sounds (default, chime, bell, ding, success) and custom sound file support #hpstream
- Add review-before-write diff preview with "Apply Always" button for file-modifying tools #gadfly3173
- Add editable session titles in chat header with inline edit mode and history sync #jhaan83
- Add auto-scroll pause when user scrolls up during streaming, resumes on scroll-to-bottom or new message #jhaan83
- Add import/export for agents and prompts with conflict resolution strategies (skip, overwrite, duplicate) #hpstream
- Add markdown rendering in permission and plan approval dialogs #dsudomoin
- Add collapsible earlier messages with show/hide toggle in MessageList #dsudomoin
- Add user message bubble color customization in settings (8 languages) #dsudomoin

🐛 Fixes
- Eliminate React re-renders during IME composition for JCEF CJK input using ref-only approach #Stackerr
- Fix contenteditable input: disable spellcheck, prevent character loss during fast typing, fix ArrowUp navigation with pasted text #jhaan83 #dsudomoin
- Fix enhance prompt output language to match source prompt language #Olexandr1904
- Fix session title persistence: migrate title on SDK session ID change, clear ID on new session, prevent focus stealing during title edit #jhaan83
- Fix custom model restoration in session state validation
- Cancel pending reject task and close diff view on Apply Always action
- Replace native select with upward-opening dropdown for sound selector (JCEF clipping fix)
- Harden security: command injection prevention in NodeJsServiceCaller (function name whitelist + env vars), path traversal protection in SoundNotificationService, permission mode whitelist, DOMPurify XSS sanitization for streaming markdown
- Fix stale closures in useSettingsWindowCallbacks via ref pattern
- Improve anchor rail sync with collapsed message count and skip hidden anchors

🔧 Improvements
- Scroll performance: IntersectionObserver in MessageAnchorRail, rAF throttle + passive listeners in ScrollControl #dsudomoin
- CSS performance: contain:layout on messages, border instead of box-shadow, remove will-change per char #dsudomoin
- Split large files into smaller focused modules: CSS (12 files), SettingsDialogs, icons (3 modules), CodexMessageConverter, NodeJsServiceCaller
- Extract shared useDialogResize hook from PermissionDialog and PlanApprovalDialog
- Use deepCopy for duplicate operations in AgentManager/PromptManager to prevent object mutation
- Translate PromptEnhancerHandler Chinese content to English
- Console forwarding only in devMode, remove excessive console.log statements`,
      zh: `✨ Features
- 新增任务完成提示音功能：5 种内置提示音（默认、风铃、铃声、叮咚、成功）及自定义音频文件支持 #hpstream
- 新增写入前 Diff 预览功能，支持"始终应用"按钮，用于文件修改类工具 #gadfly3173
- 新增聊天标题栏内联编辑模式，支持自定义会话标题并同步到历史记录 #jhaan83
- 新增流式输出时鼠标滚轮上滑自动暂停滚动，滑到底部或发送新消息时恢复 #jhaan83
- 新增 Agent 和 Prompt 导入/导出功能，支持冲突解决策略（跳过、覆盖、复制） #hpstream
- 新增权限对话框和计划审批对话框的 Markdown 渲染 #dsudomoin
- 新增消息列表中历史消息的折叠/展开功能 #dsudomoin
- 新增用户消息气泡颜色自定义（支持 8 种语言） #dsudomoin

🐛 Fixes
- 修复 JCEF 环境下CJK输入法组合输入导致的 React 重渲染问题，改用 ref-only 方案 #Stackerr
- 修复 contenteditable 输入框：禁用拼写检查、防止快速打字丢字、修复粘贴文本后方向键导航 #jhaan83 #dsudomoin
- 修复增强提示词输出语言始终为中文的问题，现在匹配源语言 #Olexandr1904
- 修复会话标题持久化：SDK 会话 ID 变更时迁移标题、新建会话时清除 ID、防止编辑标题时焦点被抢 #jhaan83
- 修复自定义模型在会话状态恢复时的验证逻辑
- 修复"始终应用"操作后取消挂起的拒绝任务并关闭 Diff 视图
- 修复 JCEF 环境下原生 select 被裁剪问题，替换为向上展开的自定义下拉框
- 安全加固：NodeJsServiceCaller 命令注入防护（函数名白名单 + 环境变量传参）、SoundNotificationService 路径遍历防护、权限模式白名单验证、流式 Markdown DOMPurify XSS 防护
- 修复 useSettingsWindowCallbacks 中的闭包过期问题，改用 ref 模式
- 改进消息锚点导航栏与折叠消息的同步，跳过隐藏的锚点

🔧 Improvements
- 滚动性能优化：MessageAnchorRail 使用 IntersectionObserver、ScrollControl 使用 rAF 节流 + passive 监听器 #dsudomoin
- CSS 性能优化：消息元素使用 contain:layout、border 替代 box-shadow、移除逐字符 will-change #dsudomoin
- 拆分大文件为小型聚焦模块：CSS（12 个文件）、SettingsDialogs、icons（3 个模块）、CodexMessageConverter、NodeJsServiceCaller
- 提取 useDialogResize 共享 hook，消除 PermissionDialog 和 PlanApprovalDialog 的重复代码
- AgentManager/PromptManager 复制操作使用 deepCopy 防止对象变异
- 将 PromptEnhancerHandler 中的中文内容翻译为英文
- 控制台转发仅在开发模式启用，移除多余的 console.log 语句`,
    },
  },
  {
    version: '0.2.1',
    date: '2026-02-21',
    content: {
      en: `✨ Features
- Filter .gitignore'd files from editor context to prevent sensitive file leakage with cached IgnoreRuleMatcher (30s TTL)
- Add "Diff expanded by default" toggle in Settings → Basic with localStorage persistence #dsudomoin

🐛 Fixes
- Stabilize streaming and prevent content loss: atomic IPC output, consistent JSON encoding for deltas, flush final content before stream end #gadfly3173
- Harden security: path traversal protection in permission-handler, stop logging API key prefix, add Content-Security-Policy meta tag to webview
- Replace hardcoded Chinese/text with i18n translation functions and add missing translations across all locales #serega0005

🔧 Improvements
- Optimize React rendering with React.memo, useCallback, useMemo and lazy-load mermaid (~500KB deferred) #gadfly3173
- Decompose ClaudeSDKToolWindow (~2700 lines) into 11 single-responsibility classes (SessionLifecycleManager, StreamMessageCoalescer, WebviewInitializer, etc.)
- Improve Russian localization: natural first-person verb forms, session→chat terminology, translate settings.prompt section #dsudomoin
- Replace Chinese log/UI messages with English and normalize Unicode emoji escape sequences`,
      zh: `✨ Features
- 过滤 .gitignore 规则匹配的文件，防止敏感文件泄漏到编辑器上下文，使用带 30 秒 TTL 缓存的 IgnoreRuleMatcher
- 新增"Diff 默认展开"开关（设置 → 基础），支持 localStorage 持久化 #dsudomoin

🐛 Fixes
- 稳定流式传输并防止内容丢失：原子化 IPC 输出、统一 delta JSON 编码、流结束前刷新最终内容 #gadfly3173
- 加固安全性：权限处理器路径遍历防护、停止记录 API Key 前缀、为 webview 添加 CSP meta 标签
- 将硬编码中文/文本替换为 i18n 翻译函数，补充所有语言环境的缺失翻译 #serega0005

🔧 Improvements
- 优化 React 渲染：使用 React.memo、useCallback、useMemo，懒加载 mermaid（延迟 ~500KB 解析） #gadfly3173
- 拆解 ClaudeSDKToolWindow（约 2700 行）为 11 个单一职责类（SessionLifecycleManager、StreamMessageCoalescer、WebviewInitializer 等）
- 改进俄语本地化：使用自然第一人称动词形式、session→chat 术语替换、翻译 settings.prompt 部分 #dsudomoin
- 将中文日志/UI 消息替换为英文，规范化 Unicode emoji 转义序列`,
    },
  },
  {
    version: '0.2',
    date: '2026-02-20',
    content: {
      en: `✨ Features
- Add message anchor navigation rail with quick-scroll dots for jumping between user messages
- Refactor custom model management to plugin-level with standalone CRUD dialog and cross-provider localStorage sync
- Add version history entry in community settings with link to changelog dialog
- Update open-source banner text with piracy warning across all 8 locales

🐛 Fixes
- Fix context window token calculation formula: include cache_read_input_tokens instead of output_tokens in all 5 code paths #gadfly3173
- Fix reserved padding-left layout shift when message anchor rail is hidden

🔧 Improvements
- Simplify token usage display by reusing extractUsedTokens with dynamic provider detection
- Add [USAGE] tag pipeline for accurate token data flow from ai-bridge to Java backend #gadfly3173
- Continue translating remaining Chinese comments to English across Java backend and React frontend
- Remove sponsor QR codes section from community settings`,
      zh: `✨ Features
- 新增消息锚点导航栏，支持快速滚动定位到各条用户消息
- 重构自定义模型管理为插件级别，新增独立 CRUD 对话框，支持跨供应商 localStorage 同步
- 在社区设置中新增版本历史入口，链接到更新日志弹窗
- 更新开源横幅文案，增加盗版警告提示（覆盖全部 8 种语言）

🐛 Fixes
- 修复上下文窗口 Token 计算公式：在全部 5 个代码路径中使用 cache_read_input_tokens 替代 output_tokens #gadfly3173
- 修复消息锚点导航栏隐藏时多余的左侧内边距导致的布局偏移

🔧 Improvements
- 简化 Token 使用量显示，复用 extractUsedTokens 并支持动态供应商检测
- 新增 [USAGE] 标签管道，实现 ai-bridge 到 Java 后端的精确 Token 数据流 #gadfly3173
- 继续将 Java 后端和 React 前端中的剩余中文注释翻译为英文
- 移除社区设置中的赞助二维码部分`,
    },
  },
  {
    version: '0.1.9-fix',
    date: '2026-02-19',
    content: {
      en: `✨ Features
- New version record pop-up window
- Add custom model support for Claude providers with per-provider model editor and model selector integration`,
      zh: `✨ Features
- 新增版本记录弹窗
- 新增 Claude 供应商自定义模型支持，支持按供应商编辑模型并集成到模型选择器`,
    },
  },
  {
    version: '0.1.9',
    date: '2026-02-19',
    content: {
      en: `✨ Features
- Add prompt template management system with backend CRUD, PromptDialog UI, and ">>" trigger detection in chat input #hpstream
- Add chat background color customization with theme-aware presets and color picker
- Add batch search grouping for consecutive grep/glob/find tool calls (SearchToolGroupBlock)
- Add collapsible accordion to TaskOutput tool block
- Add dismissible open-source banner above chat input
- Add Russian language support #dsudomoin
- Add timestamp display for history completion items with relative time formatting #hpstream
- Upgrade default models to Sonnet 4.6 and Opus 4.6, remove Opus 4.5
- Support multi-file drag and drop into chat input
- Extract hardcoded strings to resource bundles for full internationalization

🐛 Fixes
- Resolve paste-then-send race condition in chat input with debounce flush mechanism #gadfly3173
- Send full tool_result block and remove cwd file cleanup to prevent cross-session race condition #gadfly3173
- Fix markdown rendering error handling and dialog overlay click blocking
- Fix i18n pluralization for relative time display (e.g. "1 year ago" vs "1 years ago")
- Add input validation and harden prompt operations (null checks, ID format validation, hex color validation)
- Replace debounce non-null assertion with guard check to prevent runtime errors
- Batch timestamp writes to reduce N localStorage read/write cycles to 1

🔧 Improvements
- Translate all Chinese comments to English across codebase for improved accessibility
- Add truncateToolResultBlock() to limit IPC payload size (20k chars) matching Java-side threshold
- Replace per-session temp file cleanup with age-based stale cleanup (>24h) during IDE shutdown for safe concurrent sessions
- Refactor prompt template: use shared service instance, require whitespace before trigger, switch to debug log levels, remove dead code
- Simplify markdown rendering by removing redundant mountRetry and over-wrapped error fallback
- Add Russian plural forms (_one/_few/_many) for i18n`,
      zh: `✨ Features
- 新增提示词模板管理系统：后端 CRUD、PromptDialog 界面、输入框 ">>" 触发检测 #hpstream
- 新增聊天背景颜色自定义，支持主题感知预设和颜色选择器
- 新增连续搜索工具调用（grep/glob/find）的批量分组显示（SearchToolGroupBlock）
- 新增 TaskOutput 工具块的可折叠手风琴组件
- 新增聊天输入框上方的可关闭开源横幅
- 新增俄语语言支持 #dsudomoin
- 新增历史补全项的时间戳显示，支持相对时间格式化 #hpstream
- 升级默认模型到 Sonnet 4.6 和 Opus 4.6，移除 Opus 4.5
- 支持多文件拖拽到聊天输入框
- 提取硬编码字符串到资源包，实现完整国际化

🐛 Fixes
- 修复粘贴后立即发送的竞态条件，添加防抖 flush 机制 #gadfly3173
- 发送完整 tool_result 块并移除 cwd 文件清理，防止跨会话竞态条件 #gadfly3173
- 修复 Markdown 渲染错误处理和对话框遮罩层点击阻塞问题
- 修复相对时间显示的国际化复数形式（如 "1 year ago" 而非 "1 years ago"）
- 添加输入验证并加固提示词操作（空值检查、ID 格式验证、十六进制颜色验证）
- 将防抖非空断言替换为守卫检查，防止运行时错误
- 批量写入时间戳，将 N 次 localStorage 读写减少为 1 次

🔧 Improvements
- 将代码库中所有中文注释翻译为英文，提升可访问性
- 添加 truncateToolResultBlock() 限制 IPC 负载大小（20k 字符），匹配 Java 端阈值
- 将每会话临时文件清理替换为基于时间的过期清理（>24h），在 IDE 关闭时执行，支持并发会话安全
- 重构提示词模板：使用共享服务实例、触发符前需空白字符、切换为 debug 日志级别、移除死代码
- 简化 Markdown 渲染，移除冗余的 mountRetry 和过度包装的错误回退
- 添加俄语复数形式（_one/_few/_many）国际化支持`,
    },
  },
  {
    version: '0.1.8',
    date: '2026-02-12',
    content: {
      en: `✨ Features
- Add Claude Opus 4.6 model support with 1M context window
- Add preset buttons for quick provider configuration with one-click setup
- Integrate Claude and Codex provider management with unified tab interface
- Enhance DevTools action with Chrome remote debugging support
- Change file click behavior in status panel and restore diff icon
- Update Codex SDK to latest version
- Add exception error notification for better user feedback

🐛 Fixes
- Fix MCP SSE transport verification and tools retrieval
- Fix MCP STDIO server verification and improve protocol compliance
- Fix SSE endpoint and error handling issues
- Truncate long error messages to prevent webview freezing
- Preserve cursor position after dropdown selection and file-tag rendering
- Exclude cache read tokens from context window usage calculation
- Disable immediate tab creation to fix tab loading stuck issue
- Improve mermaid rendering on history load
- Use #app rect as reference for fixed positioning in zoom container
- Retrieve user-selected changes via reflection for diff operations
- Fix compile encoding on Windows

🔧 Improvements
- Change license from AGPL-3.0 to MIT for broader compatibility
- Add i18n support for provider presets and optimize rendering
- Filter environment keys in local provider and optimize model mapping
- Refactor reflection to safely handle collections
- Fix ErrorBoundary timer cleanup to prevent memory leaks
- Extract sponsors list to SPONSORS.md and simplify README
- Add Trendshift badge to README files`,
      zh: `✨ Features
- 新增 Claude Opus 4.6 模型支持，提供 1M 上下文窗口
- 新增供应商预设按钮，支持一键快速配置
- 整合 Claude 和 Codex 供应商管理，统一标签页界面
- 增强 DevTools 操作，支持 Chrome 远程调试
- 修改状态面板文件点击行为，恢复 Diff 图标
- 更新 Codex SDK 到最新版本
- 新增异常错误通知，提供更好的用户反馈

🐛 Fixes
- 修复 MCP SSE 传输验证和工具获取问题
- 修复 MCP STDIO 服务器验证，改进协议兼容性
- 修复 SSE 端点和错误处理问题
- 截断长错误消息，防止 webview 冻结
- 修复下拉选择和文件标签渲染后的光标位置保持
- 从上下文窗口使用量计算中排除缓存读取的 token
- 禁用立即创建标签页，修复标签页加载卡住问题
- 改进历史记录加载时的 mermaid 渲染
- 使用 #app rect 作为缩放容器中固定定位的参考
- 通过反射获取用户选择的更改用于 Diff 操作
- 修复 Windows 下的编译编码问题

🔧 Improvements
- 许可证从 AGPL-3.0 更改为 MIT，提升兼容性
- 为供应商预设添加国际化支持，优化渲染性能
- 过滤本地供应商中的环境变量键，优化模型映射
- 重构反射以安全处理集合类型
- 修复 ErrorBoundary 定时器清理，防止内存泄漏
- 提取赞助商列表到 SPONSORS.md，简化 README
- 在 README 中添加 Trendshift 徽章`,
    },
  },
  {
    version: '0.1.7-beta5',
    date: '2026-02-05',
    content: {
      en: `✨ Features
- Add message queue functionality: auto-queue messages when AI is processing, with queue UI above input box
- Add 5-minute timeout countdown to AskUserQuestionDialog and PlanApprovalDialog with 30-second warning banner
- Add collapse/expand functionality for permission dialogs
- Add history item editor with importance settings in OtherSettingsSection
- Add attachment block support for file chips display
- Add "Auto Open File" toggle to control ContextBar display and AI context collection
- Add history deep search feature: clears cache and reloads all session data from filesystem

🐛 Fixes
- Fix tool icon width and alignment in MCP settings
- Fix line separator handling in diff view to prevent "Wrong line separators" errors
- Fix token usage calculation for different providers (Codex/OpenAI vs Claude cache handling)
- Fix useEffect dependency issues in dialog components
- Fix potential timer memory leaks with improved cleanup logic
- Fix autoOpenFile setting to properly control AI editor context collection

🔧 Improvements
- Refactor: use centralized path utilities for homedir resolution (fix Windows symlink issues)
- Refactor: extract line separator handling to LineSeparatorUtil
- Refactor: replace CSS gap property with margin-right pattern for better browser compatibility
- Refactor: extract common LESS mixins to reduce code duplication (~254 lines reduced)
- Refactor: remove SlashCommandCache class, fetch slash commands directly from SDK
- Add Map cache size limit (100 entries) to prevent memory growth
- Add OpenAI/Codex model context limits (GPT-5.x, o3, o1 series)
- Add webfetch to collapsible tools list in GenericToolBlock
- Add frontend data validation for usage percentage
- Extract formatCountdown as shared utility function
- Add comprehensive i18n support for new dialog features`,
      zh: `✨ Features
- 新增消息队列功能：AI 处理时自动排队新消息，队列 UI 显示在输入框上方
- 新增 AskUserQuestionDialog 和 PlanApprovalDialog 的 5 分钟超时倒计时，剩余 30 秒时显示警告横幅
- 新增权限对话框折叠/展开功能
- 新增历史项编辑器，支持重要性设置（在其他设置中）
- 新增附件块支持，用于文件标签显示
- 新增"自动打开文件"开关，控制 ContextBar 显示和 AI 上下文收集
- 新增历史深度搜索功能：清除缓存并从文件系统重新加载所有会话数据

🐛 Fixes
- 修复 MCP 设置中工具图标宽度和对齐问题
- 修复 Diff 视图中行分隔符处理问题，防止"Wrong line separators"错误
- 修复不同供应商的 token 使用量计算（Codex/OpenAI vs Claude 缓存处理）
- 修复对话框组件中的 useEffect 依赖问题
- 修复定时器内存泄漏问题，改进清理逻辑
- 修复 autoOpenFile 设置对 AI 编辑器上下文收集的控制

🔧 Improvements
- 重构：使用集中式路径工具函数解析 homedir（修复 Windows 符号链接问题）
- 重构：提取行分隔符处理到 LineSeparatorUtil
- 重构：用 margin-right 模式替换 CSS gap 属性，提升浏览器兼容性
- 重构：提取公共 LESS mixins 减少代码重复（约减少 254 行）
- 重构：移除 SlashCommandCache 类，直接从 SDK 获取斜杠命令
- 添加 Map 缓存大小限制（100 条）防止内存增长
- 添加 OpenAI/Codex 模型上下文限制（GPT-5.x、o3、o1 系列）
- 在 GenericToolBlock 添加 webfetch 到可折叠工具列表
- 添加前端使用百分比数据验证
- 提取 formatCountdown 为共享工具函数
- 为新对话框功能添加完整的国际化支持`,
    },
  },
  {
    version: '0.1.7-beta4',
    date: '2026-01-31',
    content: {
      en: `✨ Features
- Add input history recording with Tab key completion and configurable settings toggle
- Add persistent storage for input history in ~/.codemoss/inputHistory.json with management UI in settings
- Add interactive Diff view with Apply/Reject buttons and state persistence across sessions
- Add local handling for new session commands (/clear, /new, /reset) to bypass confirmation dialog
- Add disk cache for slash commands with 7-day TTL and preload on component mount

🐛 Fixes
- Fix placeholder text filtering when uploading images (avoid "已上传附件:" in content)
- Fix user message copy button position overlap issue
- Fix stale input values during submission by adding cancelPendingInput
- Fix stdin handling for parameter passing in node scripts
- Fix attachment placeholder i18n (replace hardcoded Chinese with standardized English format)
- Fix new file rejection in diff view: delete file instead of restoring empty content

🔧 Improvements
- Extract completion trigger detection to dedicated useCompletionTriggerDetection hook
- Improve history completion code quality: add MAX_COUNT_RECORDS limit, custom event sync, boundary checks
- Improve chat input hover and resize handle interactions with border glow effect
- Extract reusable CopyButton component from duplicate implementations
- Refactor diff utilities: extract DiffBrowserBridge and ContentRebuildUtil classes
- Add path security validation with isPathWithinProject method and improved traversal detection
- Increase input box min-height from 3 lines to 4 lines
- Add comprehensive i18n support for history management and diff operations`,
      zh: `✨ Features
- 新增输入历史记录功能，支持 Tab 键补全，可在设置中自由开关
- 新增输入历史持久化存储（~/.codemoss/inputHistory.json），设置页面支持历史管理 UI
- 新增交互式 Diff 视图，支持 Apply/Reject 按钮和跨会话状态持久化
- 新增本地会话命令处理（/clear、/new、/reset），跳过确认对话框直接创建新会话
- 新增斜杠命令磁盘缓存（7天 TTL），组件挂载时预加载

🐛 Fixes
- 修复上传图片时占位符文本过滤问题（避免内容中出现"已上传附件:"）
- 修复用户消息复制按钮位置遮挡问题
- 修复输入提交时的过期值问题，添加 cancelPendingInput 机制
- 修复 node 脚本中 stdin 参数传递处理
- 修复附件占位符国际化问题（将硬编码中文替换为标准化英文格式）
- 修复 Diff 视图中新文件拒绝操作：删除文件而非恢复空内容

🔧 Improvements
- 重构补全触发检测到独立 hook（useCompletionTriggerDetection）
- 改进历史补全代码质量：添加 MAX_COUNT_RECORDS 限制、自定义事件同步、边界检查
- 改进输入框悬停和调整大小手柄交互，添加边框发光效果
- 提取可复用的 CopyButton 组件，消除重复实现
- 重构 Diff 工具类：提取 DiffBrowserBridge 和 ContentRebuildUtil 类
- 添加路径安全验证（isPathWithinProject 方法）和改进的路径遍历检测
- 输入框最小高度从 3 行增加到 4 行
- 为历史管理和 Diff 操作添加完整的国际化支持`,
    },
  },
  {
    version: '0.1.7-beta3',
    date: '2026-01-30',
    content: {
      en: `✨ Features
- Add tab answering status indicator with multi-state support (ANSWERING, COMPLETED, IDLE) and auto-reset
- Add copy server config button for MCP servers with clipboard integration and env/headers sanitization
- Improve MCP server discovery: expose disabled and invalid servers alongside enabled ones
- Merge global and project MCP server configurations for complete status display
- Enhance PATH with ~/.local/bin and ~/.cargo/bin for uvx/cargo tool resolution

🐛 Fixes
- Fix EDT thread safety in tab status auto-reset callback
- Fix loading state sync during streaming (check before sending event)
- Fix chat input box border-radius selector for resize handles
- Sanitize environment variables and headers when copying MCP server config
- Remove unused cacheKeys prop from ServerCard

🔧 Improvements
- Replace boolean loading state with TabAnswerStatus enum for richer status display
- Replace inline MCP log panel with dialog for cleaner UI
- Relax command whitelist to warn instead of block user-configured servers
- Add marker-based output parsing for Java-side process communication with early termination
- Replace refresh icon with sync icon and unify icon button styling across MCP components
- Reduce log verbosity (info → debug) for tab status events
- Use language-neutral "..." suffix for answering state
- Add mobile responsive styles for MCP header buttons
- Remove per-server refresh button for cleaner UI
- Add internationalization support for tab status messages`,
      zh: `✨ Features
- 新增标签页回答状态指示器，支持多状态显示（回答中、已完成、空闲）并自动重置
- 新增 MCP 服务器配置复制按钮，支持剪贴板集成并自动清理敏感的环境变量和请求头
- 改进 MCP 服务器发现：展示已禁用和无效的服务器完整状态
- 合并全局和项目级 MCP 服务器配置，提供完整状态展示
- 增强 PATH 环境变量，添加 ~/.local/bin 和 ~/.cargo/bin 以支持 uvx/cargo 工具解析

🐛 Fixes
- 修复标签页状态自动重置回调中的 EDT 线程安全问题
- 修复流式传输期间加载状态同步问题（发送事件前先检查状态）
- 修复聊天输入框 border-radius 选择器对调整手柄的影响
- 复制 MCP 服务器配置时自动清理环境变量和请求头中的敏感信息
- 移除 ServerCard 中未使用的 cacheKeys 属性

🔧 Improvements
- 用 TabAnswerStatus 枚举替换布尔加载状态，支持更丰富的状态展示
- 用对话框替换内联 MCP 日志面板，界面更简洁
- 放宽命令白名单限制，对用户配置的服务器改为警告而非阻止
- Java 端进程通信添加基于标记的输出解析，支持提前终止
- 统一 MCP 组件图标按钮样式，用同步图标替换刷新图标
- 降低标签页状态事件日志级别（info → debug）
- 回答状态使用语言无关的 "..." 后缀
- 新增 MCP 头部按钮的移动端响应式样式
- 移除每个服务器的独立刷新按钮，简化界面
- 添加标签页状态消息的国际化支持`,
    },
  },
  {
    version: '0.1.7-beta2',
    date: '2026-01-28',
    content: {
      en: `✨ Features
- Add MCP server tools fetching and caching system with STDIO and HTTP/SSE support
- Add resizable chat input box with vertical resize handles and localStorage persistence
- Add copy button for user messages with performance optimization
- Add project-specific MCP configuration support

🐛 Fixes
- Fix chat input box horizontal resize bug that caused width collapse
- Fix loading panel removal causing close confirmation dialog race condition
- Fix XSS vulnerability in file tag rendering with proper text escaping
- Fix memory leak in copy button timeout cleanup
- Fix FileReader error handling for file operations

🔧 Improvements
- Refactor ChatInputBox into modular components (header, footer, resize handles)
- Optimize large text handling with array+join (6+ seconds → <100ms for 50KB text)
- Add performance instrumentation with configurable thresholds and timing marks
- Improve security with delegated event handlers to prevent listener leaks
- Add text length thresholds to skip expensive operations (10K/50K/5K chars)
- Limit max file tags per render to 50 to prevent UI freeze
- Create centralized performance constants module (constants/performance.ts)
- Improve accessibility for resize handles with ARIA roles and keyboard support
- Add tools cache manager with expiry configuration for MCP servers
- Create React hooks for MCP tools update and management (useToolsUpdate, useServerData, useServerManagement)
- Refactor MCP status service into modular architecture (13+ new modules)
- Add comprehensive TypeScript type definitions for MCP components
- Reduce native listener re-subscriptions in ChatInputBox hooks
- Replace string concatenation with array+join in file tags and text content extraction
- Use fast Range API for text insertion >5K chars instead of slow execCommand`,
      zh: `✨ Features
- 新增 MCP 服务器工具获取和缓存系统，支持 STDIO 和 HTTP/SSE 协议
- 新增聊天输入框垂直调整大小功能，支持 localStorage 持久化
- 新增用户消息复制按钮，带性能优化
- 新增项目特定 MCP 配置支持

🐛 Fixes
- 修复聊天输入框水平调整导致宽度崩溃的问题
- 修复加载面板移除导致关闭确认对话框竞态条件的问题
- 修复文件标签渲染中的 XSS 漏洞，正确转义文本
- 修复复制按钮超时清理的内存泄漏问题
- 修复 FileReader 文件操作错误处理

🔧 Improvements
- 重构 ChatInputBox 为模块化组件（header、footer、resize handles）
- 优化大文本处理，使用数组+join（50KB 文本粘贴从 6+ 秒优化至 <100ms）
- 添加性能监控工具，支持可配置阈值和计时标记
- 改进安全性，使用委托事件处理器防止监听器泄漏
- 添加文本长度阈值跳过昂贵操作（10K/50K/5K 字符）
- 限制每次渲染最多 50 个文件标签，防止 UI 冻结
- 创建集中式性能常量模块（constants/performance.ts）
- 改进调整大小手柄的可访问性，支持 ARIA 角色和键盘操作
- 添加 MCP 服务器工具缓存管理器，支持过期配置
- 创建 MCP 工具更新和管理的 React hooks（useToolsUpdate、useServerData、useServerManagement）
- 重构 MCP 状态服务为模块化架构（新增 13+ 个模块）
- 添加 MCP 组件的完整 TypeScript 类型定义
- 减少 ChatInputBox hooks 中的原生监听器重新订阅
- 在文件标签和文本内容提取中用数组+join 替换字符串拼接
- 对超过 5K 字符的文本插入使用快速 Range API 替代缓慢的 execCommand`,
    },
  },
  {
    version: '0.1.7-beta1',
    date: '2026-01-28',
    content: {
      en: `✨ Features
- Add chat input history navigation with ArrowUp/ArrowDown keys
- Add tab rename and close confirmation features
- Add AI-powered commit message generation
- Add Codex SDK image attachment support

🐛 Fixes
- Fix MCP connection failure issue
- Fix MCP invocation issue on Windows

🔧 Improvements
- Refactor ChatInputBox into modular hooks
- Improve custom model input validation and security
- Improve Action classes thread safety`,
      zh: `✨ Features
- 聊天输入框支持上下箭头键历史记录导航
- 支持标签页重命名和关闭确认
- AI 智能生成 Git 提交消息
- Codex SDK 支持图片附件

🐛 Fixes
- 修复 MCP 连接失败问题
- 修复 Windows 系统 MCP 无法调用的问题

🔧 Improvements
- 重构 ChatInputBox 组件，拆分为独立 hooks
- 改进自定义模型输入验证和安全性
- Action 类线程安全性优化`,
    },
  },
  {
    version: '0.1.6',
    date: '2026-01-25',
    content: {
      en: `- Add custom "Other" option to AskUserQuestion dialog with textarea for custom input
- Auto-detect fnm (Fast Node Manager) nodejs path (#265)
- Fix npm package specs quoting to preserve semver operators (^~><) on Windows (#258)
- Fix macOS JCEF zoom/layout recovery after resume (#248)
- Fix MCP plugin connection and invocation issues (#266)
- Extract shell execution logic to ShellExecutor utility class for better reusability
- Use toast notifications for error messages with type-based duration (error: 5s, warning: 3s, default: 2s)
- Improve MCP status service security: command whitelist validation, unified logging, reusable functions
- Add ReDoS protection with line length limits in mcp-status-service
- Replace regex-based JSON parsing with bracket matching algorithm for better security
- Add input length limits in AskUserQuestionDialog
- Improve NpmPermissionHelper with precompiled regex and quote escaping
- Extract Toast duration constants for better maintainability
- Add i18n translations for "Other" option (en, es, fr, hi, ja, zh, zh-TW)
- Change cancel button text to "Auto" across all languages`,
      zh: `- 在 AskUserQuestion 对话框中添加自定义 "Other" 选项，支持文本输入
- 自动检测 fnm（快速 Node 管理器）的 nodejs 路径 (#265)
- 修复 Windows 上 npm 包规格引用问题，保留 semver 操作符（^~><）(#258)
- 修复 macOS JCEF 休眠恢复后的缩放/布局问题 (#248)
- 修复 MCP 插件无法正常连接调用的问题 (#266)
- 提取 shell 执行逻辑到 ShellExecutor 工具类，提升代码复用性
- 使用 toast 通知替代错误消息，根据类型设置显示时长（错误: 5秒，警告: 3秒，默认: 2秒）
- 改进 MCP 状态服务安全性：命令白名单验证、统一日志系统、提取可复用函数
- 在 mcp-status-service 中添加 ReDoS 防护，限制行长度
- 用括号匹配算法替换基于正则的 JSON 解析，提升安全性
- 在 AskUserQuestionDialog 中添加输入长度限制
- 改进 NpmPermissionHelper，添加预编译正则和引号转义
- 提取 Toast 显示时长常量，提升可维护性
- 为 "Other" 选项添加多语言翻译（en、es、fr、hi、ja、zh、zh-TW）
- 将取消按钮文本统一更改为 "Auto"`,
    },
  },
  {
    version: '0.1.6-beta3',
    date: '2026-01-24',
    content: {
      en: `- Add StatusPanel with task tracking, subagent status, and file changes undo
- Add session index cache system with in-memory caching (5min TTL) and disk persistence
- Add BashToolGroupBlock for batch command display with timeline view
- Extract and display command-message tag content from user input
- Extract settings state management into custom hooks (useProviderManagement, useCodexProviderManagement, useAgentManagement)
- Add useIsToolDenied shared hook to reduce code duplication
- Add useFileChanges hook with single/batch undo support
- Add useSubagents hook for background task status tracking
- Fix cursor position preservation during input value sync and file tag rendering
- Fix permission handling issues (JSON parse error handling, stale state cleanup, React safety)
- Fix BashToolGroupBlock expanded item scrolling by increasing max-height
- Fix BridgeDirectoryResolver filesystem sync race condition
- Refactor: remove duplicate LOG.info/debugLog calls in permission services
- Refactor: extract permission timeout as named constants with cross-reference comments
- Clean up frontend console logs`,
      zh: `- 新增状态面板（StatusPanel）：支持任务跟踪、子代理状态显示和文件变更撤销
- 新增会话索引缓存系统：内存缓存（5分钟 TTL）+ 磁盘持久化
- 新增批量命令显示组件（BashToolGroupBlock）：支持时间线视图
- 提取并显示用户输入中的 command-message 标签内容
- 提取设置状态管理到自定义 hooks（useProviderManagement、useCodexProviderManagement、useAgentManagement）
- 新增 useIsToolDenied 共享 hook，减少代码重复
- 新增 useFileChanges hook，支持单个/批量撤销功能
- 新增 useSubagents hook，用于后台任务状态跟踪
- 修复输入框光标位置：输入值同步和文件标签渲染时保持光标位置
- 修复权限处理问题（JSON 解析错误处理、过期状态清理、React 安全性）
- 修复 BashToolGroupBlock 展开项滚动问题
- 修复 BridgeDirectoryResolver 文件系统同步竞态条件
- 重构：移除权限服务中的重复 LOG.info/debugLog 调用
- 重构：提取权限超时为命名常量并添加交叉引用注释
- 清理前端 console.log 语句`,
    },
  },
  {
    version: '0.1.6-beta2',
    date: '2026-01-22',
    content: {
      en: `- Add terminal support and enhance terminal monitoring features
- Add keyboard shortcuts for Quick Fix action
- Add RunConfigMonitorService to monitor Run/Debug service output
- Add dev mode detection and DevTools support
- Add Follow IDE theme option with reliable theme detection
- Add permission isolation per IDE session
- Filter @ file search results with .gitignore rules
- Add mermaid diagram rendering support
- Add send file path to CCG from project tree context menu
- Add sponsor section to settings with i18n support
- Fix Codex usage updates from result messages
- Fix: remove redundance in terminal output
- Fix: inject IDE theme at HTML load time to prevent flash
- Fix: downgrade Claude SDK to v0.2.3
- Fix: defer run-config monitoring to EDT
- Refactor: improve code quality, memory management, and security
- Refactor: improve PermissionService code quality`,
      zh: `- 添加终端支持并增强终端监控功能
- 添加 Quick Fix 操作的键盘快捷键
- 添加 RunConfigMonitorService 监控 Run/Debug 服务输出
- 添加开发模式检测和 DevTools 支持
- 添加跟随 IDE 主题选项，支持可靠的主题检测
- 实现每个 IDE 会话的权限隔离
- 根据 .gitignore 规则过滤 @ 文件搜索结果
- 添加 mermaid 图表渲染支持
- 添加从项目树右键菜单发送文件路径到 CCG 功能
- 在设置中添加赞助商部分（支持国际化）
- 修复 Codex 使用量统计更新问题
- 修复终端输出中的冗余内容
- 修复 HTML 加载时注入 IDE 主题以防止闪烁
- 修复：降级 Claude SDK 到 v0.2.3
- 修复：将 run-config 监控推迟到 EDT
- 重构：改进代码质量、内存管理和安全性
- 重构：改进 PermissionService 代码质量`,
    },
  },
  {
    version: '0.1.6-beta1',
    date: '2026-01-19',
    content: {
      en: `- Fix dialog appearing in wrong IDEA window when multiple instances are open
- Enable streaming responses by default for smoother experience
- Fix session state occasionally becoming abnormal
- Use system native save dialog when exporting sessions
- Fix settings tab losing input when switching tabs
- Fix usage statistics accuracy
- Fix custom Node.js path compatibility issue`,
      zh: `- 修复多开IDEA时，弹窗可能跑到其他IDEA窗口的问题
- 默认开启流式回复，响应更流畅
- 修复会话状态偶尔异常的问题
- 导出会话时使用系统原生保存对话框
- 修复切换设置页签时丢失已填写内容的问题
- 修复使用统计不准确的问题
- 修复自定义Node.js路径的兼容性问题`,
    },
  },
  {
    version: '0.1.5',
    date: '2026-01-17',
    content: {
      en: `- Add batch grouping for consecutive Read and Edit tool blocks
- Add status message notifications for reconnection and other status info
- Add automatic retries mechanism
- Add Codex MCP server management (CRUD operations)
- Enhance Codex integration with file context injection (@ references)
- Support active file content auto-injection for Codex
- Add AGENTS.md instruction collection support for Codex
- Filter Codex session history by current project path
- Add acceptEdits permission mode for Codex auto-edit approval
- Auto-expand latest thinking block during streaming
- Enhance TodoPanel with current task title and stopped state display
- Add WebSearch to collapsible tool blocks
- Fix MCP popups display issue
- Fix AskUserQuestion tool result handling
- Fix UUID sync for user messages and filesystem I/O timing issue
- Resolve race condition in bridge extraction and improve path handling
- Improve Windows sandbox compatibility (use danger-full-access on Windows)
- Handle JCEF remote mode NPE with dedicated error panel
- Unify tool status indicator styles and layout adjustments
- Support local.properties to specify JDK and Node paths
- Decompose App.tsx into modular components and hooks (2652 → 306 lines)
- Decompose ChatInputBox into modular hooks architecture (8 custom hooks)
- Replace deprecated execCommand with modern Selection API
- Optimize chat interface performance with smart object reuse
- Add multi-level caching and content-visibility optimization
- Add OpenCode provider option
- Improve UI/UX and enhance i18n support`,
      zh: `- 新增连续Read和Edit工具块的批量分组显示
- 新增状态消息通知（重连等状态信息）
- 新增自动重试机制
- 新增Codex MCP服务器管理（增删改查）
- 增强Codex文件上下文注入（支持@引用）
- 支持Codex自动注入当前活动文件内容
- 支持Codex的AGENTS.md指令集合
- 按当前项目路径过滤Codex会话历史
- 新增Codex自动编辑审批的acceptEdits权限模式
- 流式输出时自动展开最新的思考块
- 增强TodoPanel显示当前任务标题和停止状态
- WebSearch加入可折叠工具块
- 修复MCP弹窗显示问题
- 修复AskUserQuestion工具结果处理
- 修复用户消息UUID同步和文件系统I/O时序问题
- 解决bridge解压竞态条件并改进路径处理
- 改进Windows沙箱兼容性（Windows使用danger-full-access模式）
- 处理JCEF远程模式空指针，提供专用错误面板和引导
- 统一工具状态指示器样式和布局调整
- 支持local.properties指定JDK和Node路径
- 重构App.tsx为模块化组件和hooks（2652行→306行）
- 重构ChatInputBox为模块化hooks架构（8个自定义hooks）
- 用现代Selection API替换已废弃的execCommand
- 优化聊天界面性能（智能对象复用）
- 添加多级缓存和content-visibility优化
- 新增OpenCode供应商选项
- 改进UI/UX并增强国际化支持`,
    },
  },
  {
    version: '0.1.5-beta4',
    date: '2026-01-13',
    content: {
      en: `- Add experimental PyCharm support with Python semantic context collection #pycharm
- Add Codex reasoning effort selector with responsive UI improvements #codex
- Add configurable send shortcut for chat input (Ctrl+Enter / Cmd+Enter)
- Add copy message button for assistant responses
- Fix ai-bridge extraction waiting mechanism improvement
- Fix ai-bridge localization issues
- Adjust Codex button container query breakpoint for better responsiveness
- Update Codex reasoning effort levels`,
      zh: `- 添加实验性 PyCharm 支持，支持 Python 语义上下文收集
- 添加 Codex 推理努力程度选择器，优化响应式 UI
- 添加可配置的发送快捷键（Ctrl+Enter / Cmd+Enter）
- 添加助手回复的复制消息按钮
- 修复 ai-bridge 解压等待机制
- 修复 ai-bridge 国际化问题
- 调整 Codex 按钮容器查询断点，提升响应式体验
- 更新 Codex 推理努力程度级别`,
    },
  },
  {
    version: '0.1.5-beta3',
    date: '2026-01-11',
    content: {
      en: `- Implement Quick Fix feature with Claude integration (right-click context menu)
- Add npm permission issue detection and auto-fix mechanism with retry support
- Add nvmd (Node Version Manager Desktop) support and custom Node.js path configuration
- Improve tab management: rename tabs to sequential format (AI1, AI2, etc.), add "New Tab" button
- Prevent closing the last tab in tool window
- Pass agent prompt per-tab instead of using global setting
- Add response size guard (1MB limit) to prevent regex issues
- Fix Windows package aiBridge issue
- Fix SDK process error display
- Fix Quick Fix timing and Settings streaming state synchronization issues
- Rename "Quick Fix with Claude" to "Ask Claude Code GUI" with i18n support (8 languages)`,
      zh: `- 实现标签页管理（多开AI功能），添加"新建标签页"按钮
- 实现Quick Fix功能与Claude集成（右键上下文菜单）
- 添加npm权限问题检测和自动修复机制，支持重试
- 添加nvmd（Node版本管理器桌面版）支持和自定义Node.js路径配置
- 防止关闭工具窗口中的最后一个标签页
- 每个标签页独立使用各自选择的智能体，而非全局设置
- 添加响应大小限制（1MB）以防止正则表达式问题
- 修复Windows打包aiBridge问题
- 修复SDK进程错误显示问题
- 修复Quick Fix时序和Settings流式状态同步问题
- 将"Quick Fix with Claude"重命名为"Ask Claude Code GUI"，支持8种语言国际化`,
    },
  },
  {
    version: '0.1.5-beta2',
    date: '2026-01-10',
    content: {
      en: `- Add streaming transmission toggle switch (Claude Code)
- Add local settings.json provider option with i18n support
- Implement SDK lazy loading architecture with concurrency control
- Add Claude getMcpServerStatus API
- Add JCEF support check and improve input handling
- Improve ai-bridge caching and cleanup mechanism
- Improve IME input handling and UI feedback
- Fix Unix permissions preservation during extraction
- Replace native title tooltips with custom CSS tooltips
- Move vConsole button to top-left corner
- Add contributing guidelines (CONTRIBUTING.md)
- Refactor README with dual AI engine features description
- Improve security and performance optimizations`,
      zh: `- 增加流式传输开关（Claude Code）
- 增加本地 settings.json Provider 选项及国际化支持
- 实现 SDK 懒加载架构，增加并发控制和安全增强
- 增加 Claude getMcpServerStatus API
- 增加 JCEF 支持检测，改进输入处理
- 优化 ai-bridge 缓存和清理机制
- 改进中文输入法处理和 UI 反馈
- 修复解压时 Unix 权限丢失问题
- 工具按钮使用自定义 CSS 提示框替代原生 title
- 将 vConsole 按钮移至左上角
- 添加贡献指南（CONTRIBUTING.md）
- 重构 README，突出双 AI 引擎特性描述
- 提升安全性和性能优化`,
    },
  },
  {
    version: '0.1.5-beta1',
    date: '2026-01-08',
    content: {
      en: `- Implement conversation rewind feature with message selection dialog and ESC shortcut support
- Add JCEF availability check with user-friendly error panel
- Optimize IME composition detection for better input accuracy
- Add draft input state to preserve content during page navigation
- Add getMcpServerStatus API for MCP server status query
- Improve security: refactor PowerShell command construction to prevent injection
- Improve performance: add caching and timeout safeguards for archive extraction
- Preserve Unix file permissions during extraction
- Add automatic cleanup of outdated ai-bridge cache on plugin version change
- Fix bridge directory null check during extraction`,
      zh: `- 实现对话回退功能，支持消息选择对话框和 ESC 快捷键
- 添加 JCEF 可用性检查，提供友好的错误提示面板
- 优化输入法组合检测，提升输入准确性
- 添加草稿输入状态，页面导航时保留内容
- 添加 getMcpServerStatus API，支持查询 MCP 服务器状态
- 安全改进：重构 PowerShell 命令构建以防止注入攻击
- 性能改进：为压缩包解压添加缓存和超时保护
- 解压时保留 Unix 文件权限
- 插件版本更新时自动清理过期的 ai-bridge 缓存
- 修复解压过程中桥接目录空指针检查`,
    },
  },
  {
    version: '0.1.4',
    date: '2026-01-07',
    content: {
      en: `- Integrate Codex conversation functionality #codex
- Implement Codex environment variable key reading
- Implement Codex provider editing
- Implement Codex agent support
- Implement Codex usage statistics
- Implement Codex enhanced prompts (actually powered by Claude)
- Implement asynchronous extraction on first launch to prevent IDEA blocking
- Disable slash command periodic update to resolve abnormal API request issues`,
      zh: `- 适配Codex对话功能
- 实现Codex读取环境变量Key的功能
- 实现Codex供应商编辑
- 实现Codex智能体
- 实现Codex使用统计
- 实现Codex增强提示词（其实走的是Claude）
- 实现首次异步解压，防止阻塞IDEA
- 禁用斜杠指令定时更新功能，解决异常定时请求接口的问题`,
    },
  },
  {
    version: '0.1.4-beta7',
    date: '2026-01-05',
    content: {
      en: `- P1 (fix) Fix permission dialog rejection issue in proxy mode
- P1 (feat) Support official subscription-based login on macOS
- P2 (fix) Resolve some error messages`,
      zh: `- P1 (fix) 修复代理模式下权限弹窗被拒绝的问题
- P1 (feat) 适配Mac下官方订阅制登录的功能
- P2 (fix) 解决某些报错提示`,
    },
  },
  {
    version: '0.1.4-beta6',
    date: '2026-01-05',
    content: {
      en: `- P0 (bug) Fix permission dialog exception causing plugin black screen issue on Windows`,
      zh: `- P0（BUG）修复权限弹窗异常导致 Windows 下插件黑屏的问题`,
    },
  },
  {
    version: '0.1.4-beta5',
    date: '2026-01-04',
    content: {
      en: `- P0 (feat) Support asking questions from CLI login state (initial) #LaCreArthur
- P1 (feat) Auto-localization based on IDEA language settings
- P1 (improve) Refine localization text details
- P1 (feat) Add enable/disable toggle for MCP servers
- P1 (feat) Add /init and /review built-in slash commands
- P1 (perf) Optimize initial slash command loading logic
- P1 (style) Polish UI details
- P2 (feat) Support Ask User Question feature
- P3 (improve) Fallback UI font to editor font #gadfly3173`,
      zh: `- P0（feat）支持从 CLI 登录状态下进行提问的功能（初版） #LaCreArthur
- P1（feat）读取 IDEA 语言信息，自动本地化
- P1（improve）完善本地化文案细节
- P1（feat）MCP 服务器支持开启/关闭功能
- P1（feat）新增 /init 和 /review 斜杠内置命令
- P1（perf）优化首次加载斜杠指令逻辑
- P1（style）优化部分 UI 细节
- P2（feat）适配 Ask User Question 功能
- P3（improve）UI 字体回落至编辑器字体 #gadfly3173`,
    },
  },
  {
    version: '0.1.4-beta3',
    date: '2026-01-02',
    content: {
      en: ``,
      zh: `- P0（feat）实现初版Agent智能体功能（提示词注入）
- P1（fix）修复进入到历史记录再回来页面对话异常问题 #ｓｕ＇ｑｉａｎｇ
- P2（fix）修复文件引用标签显示不存在文件夹的问题 #ｓｕ＇ｑｉａｎｇ
- P2（feat）完善node版本检查 #gadfly3173`,
    },
  },
  {
    version: '0.1.4-beta2',
    date: '2026-01-01',
    content: {
      en: ``,
      zh: `- P0（feat）添加强化提示功能 #xiexiaofei
- P1（feat）支持艾特多个文件的
- P1（feat）优化选中文案提示词，解决AI识别不稳定的问题
- P2（fix）修复删除会话后仍显示已删除会话的问题 #ｓｕ＇ｑｉａｎｇ
- P2（feat）取消用户发送信息MD渲染，取消默认删除换行空格
- P2（feat）增加当前字体信息展示功能
- P2（feat）增加供应商设置JSON-格式化按钮
- P3（fix）解决下拉列表点击不了的问题（PR#110产生的小问题）`,
    },
  },
  {
    version: '0.1.4-beta1',
    date: '2025-12-31',
    content: {
      en: ``,
      zh: `- P1（feat）增加读取IDE字体设置
- P2（feat）显示mcp服务连接状态 #gadfly3173e
- P3（fix）增加用户提问问题上下折叠功能（在长度超过7行触发）
- P3（UI）优化部分UI展示效果`,
    },
  },
  {
    version: '0.1.3',
    date: '2025-12-30',
    content: {
      en: ``,
      zh: `- P1（fix）完善异常情况下的错误提醒`,
    },
  },
  {
    version: '0.1.2-beta7',
    date: '2025-12-26',
    content: {
      en: ``,
      zh: `- P0（feat）默认增加CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC为"1"，降低遥测等问题
- P1（fix）减少无法操作思考模式的问题
- P1（fix）减少某些情况下一直重复编辑的问题
- P3（UI）优化输入框更多功能弹窗UI触发区域`,
    },
  },
  {
    version: '0.1.2-beta6',
    date: '2025-12-25',
    content: {
      en: ``,
      zh: `- P1（ui）将模式切换入口放到最外层
- P1（feat）修复输入法组合输入渲染残留问题 #gadfly3173e
- P2（BUG）修复主动思考按钮无法点击问题
- P3（UX）优化三级菜单弹窗交互效果`,
    },
  },
  {
    version: '0.1.2-beta5',
    date: '2025-12-25',
    content: {
      en: ``,
      zh: `- P0（fix）优化性能，解决输入框输入卡顿的问题（6000+对话也不卡）
- P1（feat）增加主动思考配置入口
- P1（fix）解决某些情况下cc-switch.db文件解析有问题
- P2（fix）再次优化代码，降低window下出现无法编辑写入的BUG
- P2（fix）再次优化代码，降低权限弹窗弹到其他窗口的概率
- P2（fix）完善工具过程展示（之前默认全展示为成功，现在会有过程）#gadfly3173e`,
    },
  },
  {
    version: '0.1.2-beta4',
    date: '2025-12-25',
    content: {
      en: ``,
      zh: `- P0（BUG）修复某些情况下，AI无法写入编辑的问题
- P2（fix）优化提示词，解决#Lxxx-xxx 类型引入无法被AI准确理解的问题
- P2（feat）实现模式切换持久化存储（不会随编辑器关闭而重置）
- P3（feat）实现代码块区域复制功能`,
    },
  },
  {
    version: '0.1.2-beta3',
    date: '2025-12-24',
    content: {
      en: ``,
      zh: `- P0（feat）实现Claude Code 模式切换功能（包括全自动权限模式）
- P1（UI）优化了输入框底部按钮区域交互样式
- P3（UI）优化了代码块展示样式`,
    },
  },
  {
    version: '0.1.2-beta2',
    date: '2025-12-23',
    content: {
      en: ``,
      zh: `- P0（BUG）解决斜杠指令无法弹出的问题
- P3（UI）增加90%字体的设置样式
- P3（UI）优化历史对话记录样式间距过大问题（统一为对话过程中那种紧凑样式）
- P3（UI）修复亮色模式下某些样式问题`,
    },
  },
  {
    version: '0.1.2',
    date: '2025-12-21',
    content: {
      en: ``,
      zh: `- 增加字体缩放功能
- 增加DIFF对比功能
- 增加收藏功能
- 增加修改标题功能
- 增加根据标题搜索历史记录功能
- 修复 alwaysThinkingEnabled 失效问题`,
    },
  },
  {
    version: '0.1.1-beta4',
    date: '2025-12-18',
    content: {
      en: ``,
      zh: `- 解决 开启多个IDEA终端，权限弹窗 异常问题
- 支持消息导出功能 #hpstream
- 修复删除历史记录的某个小bug
- 整体优化部分逻辑代码 #gadfly3173e`,
    },
  },
  {
    version: '0.1.1',
    date: '2025-12-11',
    content: {
      en: ``,
      zh: `- P0（feat）实现当前打开的文件路径（将当前打开的文件信息默认发送给AI）
- P0（feat）实现国际化功能
- P0（feat）重构供应商管理列表，支持导入cc-switch配置
- Pfeat）实现文件支持拖拽入输入框的功能（#gadfly3173 PR）
- P1（feat）增加删除历史会话功能（由群友 PR）
- P1（feat）增加Skills功能（由群友 PR）
- P1（feat）增加右键选中代码，发送到插件的功能（#lxm1007 PR）
- P1（fix）完善和重构 @文件功能，使@文件功能变得好用
- P2（fix）解决输入框部分快捷操作失效的问题`,
    },
  },
  {
    version: '0.0.9',
    date: '2025-12-05',
    content: {
      en: ``,
      zh: `- P0（feat）支持基础版本的MCP
- P0（fix）解决window下，输入某些字符导致错误的问题
- P0（fix）解决window下，使用node安装claude路径无法识别的问题
- P0（fix）解决输入框光标无法快捷移动的问题
- P0（fix）修改配置页面，之前只能展示两个字段，现在可以配置和展示多个字段
- P1（feat）增加回到顶部，或者回到底部 按钮功能
- P2（feat）支持文件信息点击跳转功能
- P2（UI）优化权限弹窗样式
- P2（fix）解决DIFF组件统计不精准的问题
- P3（fix）打开历史会话自动定位到最底部
- P3（fix）优化文件夹可点击效果
- P3（fix）优化输入框工具切换icon
- P3（fix）取消MD区域文件可点击功能
- P3（UI）解决渠道删除按钮背景颜色问题
- P3（fix）将点击供应商链接调跳转改为复制链接，以防止出现问题`,
    },
  },
  {
    version: '0.0.8',
    date: '2025-12-02',
    content: {
      en: ``,
      zh: `- P0（feat）增加主动调整Node路径的功能，用以适配五花八门的Node路径
- P1（feat）增加白色主题
- P1（feat）将渠道配置功能与cc-switch解耦，防止规则改变导致渠道丢失
- P1（feat）增加各种错误情况下的提示功能，减少空白展示情况
- P1（feat）优化@文件功能（回车发送问题还未解决）
- P2（fix）解决 运行命令 右侧小圆点总是展示置灰的问题
- P2（fix）解决对话超时后，新建对话，原来的对话还在执行，点停止按钮也没反应
- P2（UX）优化多处其他UI以及交互细节
- P3（chore）插件兼容23.2版本IDEA版本`,
    },
  },
  {
    version: '0.0.7-beta2',
    date: '2025-12-01',
    content: {
      en: ``,
      zh: `- P0: 重构代码 channel-manager.js 和 ClaudeSDKBridge.java 主代码
- P1: 解决某些三方API兼容性问题`,
    },
  },
  {
    version: '0.0.7',
    date: '2025-11-30',
    content: {
      en: ``,
      zh: `- P0: 支持选择 Opus4.5 进行提问
- P0: 将权限弹窗由系统弹窗改为页面内弹窗，并且增加了允许且不再询问的功能
- P1: 重构展示区域UI效果
- P3: 优化顶部按钮展示问题
- P3: 优化Loding样式
- P5: 优化样式细节`,
    },
  },
  {
    version: '0.0.6',
    date: '2025-11-27',
    content: {
      en: ``,
      zh: `- 重构 输入框UI交互
- 输入框 支持发送图片
- 输入框 支持模型容量统计
- 优化 数据统计页面 UI样式
- 优化 设置页面侧边栏展示样式
- 重构 多平台兼容性问题
- 解决某些特殊情况下响应无法中断的BUG`,
    },
  },
  {
    version: '0.0.5',
    date: '2025-11-26',
    content: {
      en: ``,
      zh: `- 增加使用统计
- 解决Window下新建问题按钮失效问题
- 优化一些细节样式`,
    },
  },
  {
    version: '0.0.4',
    date: '2025-11-24',
    content: {
      en: ``,
      zh: `- 实现简易版本cc-switch功能
- 解决一些小的交互问题`,
    },
  },
  {
    version: '0.0.3',
    date: '2025-11-23',
    content: {
      en: ``,
      zh: `- 解决一些核心交互阻塞流程
- 重构交互页面UI展示`,
    },
  },
  {
    version: '0.0.2',
    date: '2025-11-21',
    content: {
      en: ``,
      zh: `完成简易的，GUI对话 权限控制功能



文件写入功能展示




##### 11月20日

完成简易的，GUI对话基础页面



完成简易的，GUI对话页面，历史消息渲染功能



完成简易的，GUI页面，对话 + 回复 功能（**完成 claude-bridge 核心**）



##### 11月19日（v0.0.1） - 实现历史记录读取功能`,
    },
  },
];
